### PR TITLE
Deprecation notices are now shown to the compiler

### PR DESCRIPTION
**Pull request by danielmarschall**

### CODE REVIEW

**Comment by MHumm** [comment]
While I understand your improvement we have to check first if that meets the current minimum supported compiler requirement. This is 10.1 at the moment.

**Comment by danielmarschall** [comment]
Bad timing :-( Just a few weeks ago I have uninstalled Delphi 10 and replaced it with Delphi 11.

Do you know if deprecation-messages were available back then in version 10.1 ?

**Comment by MHumm** [comment]
I already asked in the German Delphi Praxis forum now, but we'll have to wait for the answer. Even being an EMBT MVP  since a few weeks does not mean I know everything ;-)

**Comment by MHumm** [comment]
Ok, forum says that's supported since D2009. So I'll accept this one.

**Pull request merged**
